### PR TITLE
WIP: Maybe :. Elfield

### PR DESCRIPTION
**Pull request by o1lo01ol1o**
WIP addressing #1.  This ended up being fairly mechanical and considerably less painful in terms of appeasing GHCs constraint handling than I had anticipated.  Building the `Fold` with `rpureConstraints` is much smoother than trying to guarantee the constraint "through" the interpretation functor, kudos for figuring that out.

### CODE REVIEW

**Comment by o1lo01ol1o** [comment]
@adamConnerSax I'm going to leave the architecting to you since there's now some non-trivial duplication of newtypes and classes; probably these should be consolidated into whatever larger API you would like to have.

**Comment by o1lo01ol1o** [comment]
So when you have an idea of what that should look like, ping me and I'll adapt the PR.

**Comment by adamConnerSax** [comment]
This is excellent!  Thanks so much. 
You generalized the folds pieces as well! I recall it took me a long long time to get the Folds stuff working so I'm not surprised you were running into similar issues.
Does your stuff solve your immediate issues?  Then I can take my time--things are busy!--and figure out how to consolidate all this smoothly before releasing a new version.

**Comment by o1lo01ol1o** [comment]
Yes, take your time.  The only thing I may add to this is a set of benchmarks against MonoidalMap groupbys now that @acowley [figured out my implementation errors](https://gist.github.com/o1lo01ol1o/0a65c5b5b3ad158c52772f7ddd72d2f3).  I suspect they may be faster to calculate than the `Fold` versions.

**Comment by adamConnerSax** [comment]
I think I'm going to merge this as is, add back what I can and maybe add some combinators to help with anything mappable to/from ```Maybe :. ElField". People can manage the duplication via qualified imports, I think.  I'm not sure the generalization is worth it since ```Maybe :. ElField``` is the thing you have to map everything else to/from to do anything useful.

**Pull request merged**
